captainVersion: 4
services:
    $$cap_appname-db:
        image: postgres:$$cap_postgres_version
        environment:
            POSTGRES_USER: $$cap_db_user
            POSTGRES_PASSWORD: $$cap_db_pass
            POSTGRES_DB: fusionauth
        restart: unless-stopped
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-fusionauth:
        image: fusionauth/fusionauth-app:$$cap_fusionauth_version
        depends_on:
            - $$cap_appname-db
        environment:
            DATABASE_URL: jdbc:postgresql://srv-captain--$$cap_appname-db:5432/fusionauth
            DATABASE_ROOT_USER: $$cap_db_user
            DATABASE_ROOT_PASSWORD: $$cap_db_pass
            DATABASE_USER: $$cap_db_user
            DATABASE_PASSWORD: $$cap_db_pass
            FUSIONAUTH_MEMORY: $$cap_fusion_memory
            FUSIONAUTH_URL: http://srv-captain--$$cap_appname-fusionauth:9011
            SEARCH_ENGINE_TYPE: database
        restart: unless-stopped
        volumes:
            - $$cap_appname-fusionauth-config:/usr/local/fusionauth/config
        caproverExtra:
            containerHttpPort: $$cap_container_port
caproverOneClickApp:
    variables:
        - id: $$cap_db_user
          label: Database user
          defaultValue: fusion
          validRegex: /^([a-zA-Z0-9])+$/
        - id: $$cap_db_pass
          label: Database password
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_fusionauth_version
          label: FusionAuth Version
          defaultValue: 1.7.2
          description: 'See tags at: https://hub.docker.com/r/fusionauth/fusionauth-app/tags'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_fusion_memory
          label: Fusion Memory
          defaultValue: 256M
          description: ''
          validRegex: /^([a-zA-Z0-9])+$/
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: '9.6'
          description: ''
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_container_port
          label: Container TCP Port
          defaultValue: '9011'
          description: Internal port for Fusion Auth container to listens to.
          validRegex: /^([0-9])+$/
    instructions:
        start: >-
            FusionAuth is a modern platform for Customer Identity and Access Management (CIAM).
        end: FusionAuth is deployed and available as srv-captain--$$cap_appname-fusionauth:9011 to other apps
    displayName: FusionAuth NO ELASTIC
    isOfficial: false
    description: FusionAuth is a scalable, identity and user management platform built for devs - NO ELASTIC Version
    documentation: 'Adapted from: https://github.com/FusionAuth/fusionauth-containers'
