captainVersion: 4
services:
  $$cap_appname:
    image: jboss/jbpm-server-full:$$cap_jbpm_version
    container_name: jbpm-server-full
    restart: always
    ports:
      - '8080:8080'
      - '8001:8001'
    volumes:
      - $$cap_wb_git_path:/opt/jboss/wildfly/bin/.niogit:Z
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: srv-captain--$$cap_appname-postgres
    depends_on:
      - $$cap_appname-postgres
    caproverExtra:
      JcontainerHttpPort: 8080
  $$cap_appname-postgres:
    image: postgres:$$cap_postgres_version
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm
      POSTGRES_DB: jbpm

caproverOneClickApp:
  variables:
    - id: $$cap_jbpm_version
      label: jBPM Version
      defaultValue: 'latest'
      description: 'The version of jBPM server to use.'
    - id: $$cap_wb_git_path
      label: Local Git Path
      defaultValue: '/home/myuser/wb_git'
      description: 'The local path where the Git repository will be stored.'
    - id: $$cap_postgres_version
      label: PostgreSQL Version
      defaultValue: 'latest'
      description: 'The version of PostgreSQL to use.'
  instructions:
        start: |-
            The jBPM Server Full Docker image is an easy way get started with jBPM.
            More details: https://www.jbpm.org
        end: |-
            jBPM has been successfully deployed!
  displayName: jBPM
  isOfficial: false
  description: jBPM is a toolkit for building business applications to help automate business processes and decisions
  documentation: See https://www.jbpm.org/
