captainVersion: 4
services:
  $$cap_appname:
    image: grafana/loki:$$cap_loki_version
    ports:
    - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
caproverOneClickApp:
  variables:
    - id: '$$cap_loki_version'
      label: Loki Version
      defaultValue: '2.8.2'
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/grafana/loki/tags
      validRegex: '/.{1,}/'
  instructions:
    start: |-
      Loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus. It is designed to be very cost effective and easy to operate.
    end: |-
      Loki has been deployed and is accessible on port 3100. You can now start collecting logs and querying them with Grafana.
  displayName: Loki
  isOfficial: false
  description: Loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus.
  documentation: This docker-compose is taken from https://github.com/grafana/loki
