captainVersion: 4
services:
    $$cap_appname:
        image: 1dev/server:$$cap_ant_version
        volumes:
            - $$cap_appname-data-dock:/var/run/docker.sock
            - $$cap_appname-data:/opt/onedev
        restart: always
        ports:
            - '6610:6610'
            - '6611:6611'
        environment:

        caproverExtra:
            containerHttpPort: 6610
caproverOneClickApp:
    variables:
        - id: $$cap_ant_version
          label: OneDev
          description: Choose the latest version of OneDev Server from https://hub.docker.com/r/1dev/server/tags
          defaultValue: latest
    instructions:
        start: |-
            Build OneDev server
        end: |-
            OneDev has been successfully deployed!
    displayName: OneDev
    isOfficial: false
    description: Super Easy All-In-One DevOps Platform
