---
captainVersion: 4
services:
  $$cap_appname:
    image: owncloud/server:$$cap_owncloud_version
    restart: always
    depends_on:
      - $$cap_appname-mariadb
      - $$cap_appname-redis
    environment:
        OWNCLOUD_DOMAIN: $$cap_owncloud_domain
        OWNCLOUD_TRUSTED_DOMAINS: $$cap_owncloud_trusted_domains
        OWNCLOUD_DB_TYPE: mysql
        OWNCLOUD_DB_NAME: owncloud
        OWNCLOUD_DB_USERNAME: owncloud
        OWNCLOUD_DB_PASSWORD: owncloud
        OWNCLOUD_DB_HOST: srv-captain--$$cap_appname-mariadb
        OWNCLOUD_ADMIN_USERNAME: $$cap_admin_password
        OWNCLOUD_ADMIN_PASSWORD: $$cap_admin_username
        OWNCLOUD_MYSQL_UTF8MB4: true
        OWNCLOUD_REDIS_ENABLED: true
        OWNCLOUD_REDIS_HOST: srv-captain--$$cap_appname-redis
    volumes:
      - files:/mnt/data
  $$cap_appname-mariadb:
    image: mariadb:10.6
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: owncloud
        MYSQL_USER: owncloud
        MYSQL_PASSWORD: owncloud
        MYSQL_DATABASE: owncloud
    command:
      - --max-allowed-packet=128M
      - --innodb-log-file-size=64M
    volumes:
      - mysql:/var/lib/mysql
  $$cap_appname-redis:
    image: redis:6
    restart: always
    command:
      - --databases
      - "1"
    volumes:
      - redis:/data
volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
caproverOneClickApp:
  variables:
    - id: $$cap_owncloud_version
      label: OwnCloud Version
      defaultValue: "10.9"
      description: The version of OwnCloud server to use.
    - id: $$cap_owncloud_domain
      label: OwnCloud Domain
      defaultValue: localhost
      description: The domain of the OwnCloud server.
    - id: $$cap_owncloud_trusted_domains
      label: OwnCloud Trusted Domains
      defaultValue: localhost
      description: The trusted domains for the OwnCloud server.
    - id: $$cap_admin_username
      label: Admin Username
      defaultValue: admin
      description: The admin username for the OwnCloud server.
    - id: $$cap_admin_password
      label: Admin Password
      defaultValue: password
      description: The admin password for the OwnCloud server.
  instructions:
    start: Deploying Owncloud...
    end: Owncloud has been deployed! Check the logs for more information.
  displayName: Owncloud
  isOfficial: false
  description: ownCloud, your collaboration tool The most essential productivity
    tool since email Store. Share. Work.
