captainVersion: 4
services:
    $$cap_appname:
        image: supertokens/supertokens-postgresql:$$cap_st_version
        restart: always
        environment:
            API_KEYS: $$cap_st_api_keys
            DISABLE_TELEMETRY: true
            POSTGRESQL_USER: $$cap_pg_user
            POSTGRESQL_PASSWORD: $$cap_pg_pass
            POSTGRESQL_HOST: $$cap_pg_host
            POSTGRESQL_PORT: 5432
            POSTGRESQL_DATABASE_NAME: $$cap_pg_db
        caproverExtra:
            containerHttpPort: 3567
caproverOneClickApp:
    variables:
        - id: $$cap_st_version
          label: SuperTokens Version
          description: Choose the latest version of SuperTokens from https://hub.docker.com/r/supertokens/supertokens-postgresql/tags
          defaultValue: 3.10
        - id: $$cap_st_api_keys
          label: API Keys
          description: 'This can be empty, alternatively, an example value is "Akjnv3iunvsoi8=-sackjij3ncisds,asnj9=asdcda-OI982JIUN=-a". Notice the , in the string which separates the two keys "Akjnv3iunvsoi8=-sackjij3ncisds" and "asnj9=asdcda-OI982JIUN=-a". In the backend SDK, you should only provide one of these keys. For more info read https://supertokens.com/docs/emailpassword/common-customizations/core/api-keys'
          defaultValue: ''
        - id: $$cap_pg_user
          label: Postgres Username
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_pg_pass
          label: Postgres Password
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_pg_db
          label: Postgres Default Database
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_pg_host
          label: Postgres Host
          description: 'Postgres host. This could be Caprover postgres using srv-captain--'
          validRegex: /.{1,}/

    instructions:
        start: |-
            SuperTokens is an open source authentication solution.
            More details: https://github.com/supertokens/supertokens-core
        end: |-
            SuperTokens has been successfully deployed!
    displayName: SuperTokens - No Database
    isOfficial: false
    description: An open source authentication solution (works best with create-react-app). This was based off christopher-kapic implementation
    documentation: See https://github.com/supertokens/supertokens-core
